//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webservice_Console.WebserviceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/DTO")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebserviceRef.IWebservice_Berthouzoz_Favre")]
    public interface IWebservice_Berthouzoz_Favre {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentById", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentByIdResponse")]
        Webservice_Console.WebserviceRef.Student GetStudentById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentById", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<Webservice_Console.WebserviceRef.Student> GetStudentByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentByUsername", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentByUsernameResponse")]
        Webservice_Console.WebserviceRef.Student GetStudentByUsername(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentByUsername", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetStudentByUsernameResponse")]
        System.Threading.Tasks.Task<Webservice_Console.WebserviceRef.Student> GetStudentByUsernameAsync(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/AddStudent", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/AddStudentResponse")]
        int AddStudent(string Username, float Balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/AddStudent", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/AddStudentResponse")]
        System.Threading.Tasks.Task<int> AddStudentAsync(string Username, float Balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/ChargeAccount", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/ChargeAccountResponse")]
        void ChargeAccount(int id, float balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/ChargeAccount", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/ChargeAccountResponse")]
        System.Threading.Tasks.Task ChargeAccountAsync(int id, float balance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaById", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaByIdResponse")]
        int GetQuotaById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaById", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaByIdResponse")]
        System.Threading.Tasks.Task<int> GetQuotaByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaByUsername", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaByUsernameResponse")]
        int GetQuotaByUsername(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaByUsername", ReplyAction="http://tempuri.org/IWebservice_Berthouzoz_Favre/GetQuotaByUsernameResponse")]
        System.Threading.Tasks.Task<int> GetQuotaByUsernameAsync(string Username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebservice_Berthouzoz_FavreChannel : Webservice_Console.WebserviceRef.IWebservice_Berthouzoz_Favre, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Webservice_Berthouzoz_FavreClient : System.ServiceModel.ClientBase<Webservice_Console.WebserviceRef.IWebservice_Berthouzoz_Favre>, Webservice_Console.WebserviceRef.IWebservice_Berthouzoz_Favre {
        
        public Webservice_Berthouzoz_FavreClient() {
        }
        
        public Webservice_Berthouzoz_FavreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Webservice_Berthouzoz_FavreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Webservice_Berthouzoz_FavreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Webservice_Berthouzoz_FavreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Webservice_Console.WebserviceRef.Student GetStudentById(int id) {
            return base.Channel.GetStudentById(id);
        }
        
        public System.Threading.Tasks.Task<Webservice_Console.WebserviceRef.Student> GetStudentByIdAsync(int id) {
            return base.Channel.GetStudentByIdAsync(id);
        }
        
        public Webservice_Console.WebserviceRef.Student GetStudentByUsername(string Username) {
            return base.Channel.GetStudentByUsername(Username);
        }
        
        public System.Threading.Tasks.Task<Webservice_Console.WebserviceRef.Student> GetStudentByUsernameAsync(string Username) {
            return base.Channel.GetStudentByUsernameAsync(Username);
        }
        
        public int AddStudent(string Username, float Balance) {
            return base.Channel.AddStudent(Username, Balance);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentAsync(string Username, float Balance) {
            return base.Channel.AddStudentAsync(Username, Balance);
        }
        
        public void ChargeAccount(int id, float balance) {
            base.Channel.ChargeAccount(id, balance);
        }
        
        public System.Threading.Tasks.Task ChargeAccountAsync(int id, float balance) {
            return base.Channel.ChargeAccountAsync(id, balance);
        }
        
        public int GetQuotaById(int id) {
            return base.Channel.GetQuotaById(id);
        }
        
        public System.Threading.Tasks.Task<int> GetQuotaByIdAsync(int id) {
            return base.Channel.GetQuotaByIdAsync(id);
        }
        
        public int GetQuotaByUsername(string Username) {
            return base.Channel.GetQuotaByUsername(Username);
        }
        
        public System.Threading.Tasks.Task<int> GetQuotaByUsernameAsync(string Username) {
            return base.Channel.GetQuotaByUsernameAsync(Username);
        }
    }
}
